_target_: configs.config
defaults:
  - _self_

data:
  path_to_raw_data_report: '../../data/raw/heart_cleveland.csv'
  path_to_raw_data: '../data/raw/heart_cleveland.csv'
  path_to_preprocessed_X_train: '../data/train/X_train.csv'
  path_to_preprocessed_y_train: '../data/train/y_train.csv'
  path_to_preprocessed_X_test: '../data/test/X_test.csv'
  path_to_preprocessed_y_test: '../data/test/y_test.csv'
  path_to_predictions: '../data/predictions/preds.csv'

features:
  cat_features:
    - 'sex'
    - 'cp'
    - 'fbs'
    - 'restecg'
    - 'exang'
    - 'slope'
    - 'ca'
    - 'thal'
  num_features:
    - 'age'
    - 'trestbps'
    - 'chol'
    - 'thalach'
    - 'oldpeak'
  target_feature: 'condition'

transformer:
  path_to_transformer: '../models/transformer.pkl'

model:
  clf_name: 'KNeighborsClassifier'
  clf_params: {
    n_neighbors: 10,
    weights: 'uniform',
    metric: 'minkowski'
  }
  path_to_model: '../models/models.pkl'
  n_folds: 5
  test_size: 0.2
  random_state: 256

path_to_report: "../../reports"
path_to_metrics: '../metrics/metrics.csv'


